# Generated by Django 3.2.17 on 2023-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='descripiton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.TextField(max_length=64, unique=True),
        ),
    ]
